<?php

namespace Iapps\HoldingAccountService\Common;

class MessageCode{

    const CODE_HOLDING_ACCOUNT_CREATE_SUCCESS = 15001;
    const CODE_HOLDING_ACCOUNT_CREATE_FAILED = 15002;
    const CODE_HOLDING_ACCOUNT_ALREADY_EXISTS = 15003;
    const CODE_HOLDING_ACCOUNT_NOT_EXISTS = 15004;
    const CODE_HOLDING_ACCOUNT_UPDATE_SUCCESS = 15005;
    const CODE_HOLDING_ACCOUNT_UPDATE_FAILED = 15006;
    const CODE_HOLDING_ACCOUNT_INACTIVE = 15007;
    const CODE_HOLDING_ACCOUNT_FOUND = 15008;
    const CODE_HOLDING_ACCOUNT_NOT_FOUND = 15009;
    const CODE_INVALID_PAYMENT_AMOUNT = 15010;
    const CODE_INVALID_PASSCODE = 15011;
    const CODE_INVALID_DEPOSIT_AMOUNT = 15012;
    const CODE_PAYMENT_FAILED = 15013;
    const CODE_INVALID_REQUEST_AMOUNT = 15014;
    const CODE_INVALID_TRANSACTIONID = 15015;
    const CODE_COMPUTE_FEE_FAILED = 15016;
    const CODE_AUTOCANCEL_PROCESSED = 15017;

    const CODE_ADD_HOLDING_ACCOUNT_TRANSACTION_SUCCESS = 15018;
    const CODE_ADD_HOLDING_ACCOUNT_TRANSACTION_FAILED = 15019;
    const CODE_INSUFFICIENT_FUND = 15020;
    const CODE_DEDUCT_FUND_FAILED = 15021;
    const CODE_INVALID_TRANSACTION_TYPE = 15022;

    const CODE_HOLDING_ACCOUNT_REQUEST_NOT_FOUND = 15023;
    const CODE_HOLDING_ACCOUNT_REQUEST_SUCCESS = 15024;
    const CODE_HOLDING_ACCOUNT_REQUEST_FAILED = 15025;
    const CODE_HOLDING_ACCOUNT_REQUEST_CANCEL_SUCCESS = 15026;
    const CODE_HOLDING_ACCOUNT_REQUEST_CANCEL_FAILED = 15027;
    const CODE_HOLDING_ACCOUNT_REQUEST_COMPLETE_SUCCESS = 15028;
    const CODE_HOLDING_ACCOUNT_REQUEST_COMPLETE_FAILED = 15029;

    const CODE_USER_NOT_FOUND = 15030;
    const CODE_PREVIOUS_REQUEST_ACTIVE = 15031;
    const CODE_PREVIOUS_TOPUP_REQUEST_ACTIVE = 15032;
    const CODE_PREVIOUS_WITHDRAWAL_REQUEST_ACTIVE = 15033;

    const CODE_GET_HOLDING_ACCOUNT_HISTORY_SUCCESS  = 15034;
    const CODE_GET_HOLDING_ACCOUNT_HISTORY_NOT_FOUND  = 15035;

    const CODE_INVALID_FEE_TYPE                         = 15036;

    const CODE_GET_HOLDING_ACCOUNT_CONFIG_SUCCESS = 15037;
    const CODE_GET_HOLDING_ACCOUNT_CONFIG_FAILED = 15038;
    const CODE_ADD_HOLDING_ACCOUNT_CONFIG_SUCCESS = 15039;
    const CODE_ADD_HOLDING_ACCOUNT_CONFIG_FAILED = 15040;
    const CODE_EDIT_HOLDING_ACCOUNT_CONFIG_SUCCESS = 15041;
    const CODE_EDIT_HOLDING_ACCOUNT_CONFIG_FAILED = 15042;
    const CODE_CURRENCY_NOT_SUPPORTED = 15043;
    const CODE_SERVICE_NOT_FOUND = 15044;


    const CODE_WITHDRAWAL_NOT_ALLOWED = 15045;

    const CODE_EXCEEDED_TOPUP_LIMIT = 5511;

    const CODE_JOB_PROCESS_FAILED = 15200;
    const CODE_JOB_PROCESS_PASSED = 15201;
}